#
# (C) Copyright 2007 - 2013 Tensilica Inc.
# (C) Copyright 2014 - 2016 Cadence Design Systems Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_CMD_BOOTM) += bootm.o

obj-y 	+= misc.o time.o
